name: live2p_test
channels:
 - conda-forge
dependencies:
 - caiman
 - python
 - pip
 - pandas
 - seaborn
 - xarray
 - jupyterlab
 - notebook
 - pip:
   - websockets
   - scanimage-tiff-reader
   - pytest