name: live2p
channels:
 - conda-forge
dependencies:
 - caiman
 - python
 - pip
 - pandas
 - seaborn
 - xarray
 - jupyterlab
 - notebook
 - pip:
   - websockets=12.0
   - scanimage-tiff-reader
   - pytest